version: '3.8'

services:
  input-app:
    build:
      context: .
      dockerfile: input-app/Dockerfile
    ports:
      - "5173:80"
    networks:
      - qr_monsin_network

  restore-app:
    build:
      context: .
      dockerfile: restore-app/Dockerfile
    env_file:
      - ./restore-app/.env
    depends_on:
      - restore-server
    environment:
      WAIT_FOR_HOST: "restore-server:3000"
    ports:
      - "5174:80"
    networks:
      - qr_monsin_network

  restore-server:
    build:
      context: .
      dockerfile: restore-server/Dockerfile
    env_file:
      - ./restore-server/.env
    ports:
      - "3000:3000"
    networks:
      - qr_monsin_network

networks:
  qr_monsin_network:
    driver: bridge
